### ISSUE TITLE
What's the file format for clarification need evaluation

### ISSUE THREAD

**Issue by iwangjian** [aliannejadi/ClariQ#2]
Hi, in ```clariq_eval_tool.py```,  the function ```evaluate_clarification_need``` needs ```train.json``` and ```dev.json``` for evaluation, would you please provide these two files or the sample format of these two files?

**Comment by aliannejadi** [comment]
Hi Jian,
Thank you for raising this issue. I will work on it today.
Moh.

**Comment by aliannejadi** [comment]
@iwangjian please pull and merge. it must work now.
