### ISSUE TITLE
About dataset 

### ISSUE THREAD

**Issue by iwangjian** [aliannejadi/ClariQ#3]
In both train set and dev set, each given `initial_request` has a list of clarification questions with corresponding answers. Does that mean all these clarification questions are ground-truth labels of the request? If so, which question should be ranked as the top-1? It seems that we only consider the top-1 ranked question for document relevance evaluation.

**Comment by aliannejadi** [comment]
Thank you, Jian. Yes, we only take the first question for document relevance evaluation. 
For this task, you can use `single_turn_train_eval.pkl` as training labels. In this file, you have the document relevance performance after asking each question in the training/dev set. Hope it helps. please let us know if you have further questions.

**Comment by iwangjian** [comment]
I have tried to get the document relevance performance using ```single_turn_train_eval.pkl``` after asking each question in the dev set, but the best questions I obtained are different from the ```sample_runs/dev_best_q```.  Without these labels, it's pretty hard to train our question ranking models. Could you please share how to extract the best questions in the training/dev set?

**Comment by aliannejadi** [comment]
Thank you for your question, Jian. We average the impact of every question on all facets of the same topic. Then we take the question that leads to the highest average document relevance performance for all facets. Please let me know if this clarifies the issue here.

**Comment by iwangjian** [comment]
Got it! Thank you.
