### ISSUE TITLE
How to get top10k documents

### ISSUE THREAD

**Issue by ShiyuNee** [aliannejadi/ClariQ#5]
How can i get top10k ducuments after having uuid?

**Comment by aliannejadi** [comment]
Please send me an email, I can share the index files we have created for each topic.

**Comment by ShiyuNee** [comment]
> Please send me an email, I can share the index files we have created for each topic.

Ok, Thank you

**Comment by ShiyuNee** [comment]
> Please send me an email, I can share the index files we have created for each topic.

Oh,i'm sorry, it's my fault because i get wrong uuids(my input is wrong), i have solved this problem now.

Thank you!
