### ISSUE TITLE
How to identify a single topic?

### ISSUE THREAD

**Issue by ShiyuNee** [aliannejadi/ClariQ#6]
I counted the number of topics whose clarification need is 1, and found the number is 29. I want to know how to identify a single topic.

The reason is: i found that there are no single topics in Qulac, so i want to know the difference.

Thank you!

**Comment by aliannejadi** [comment]
The "single topics" are those from the TREC Web track that had only one facet. They are not the same as those who have clarification need label of 1. It's easy to find them if you look at the topic--facet mapping that we have in the dataset, you can find those that have only one facet. So they are the "single topics".

**Comment by ShiyuNee** [comment]
> The "single topics" are those from the TREC Web track that had only one facet. They are not the same as those who have clarification need label of 1. It's easy to find them if you look at the topic--facet mapping that we have in the dataset, you can find those that have only one facet. So they are the "single topics".

Thanks for helping, i will try to find these topics.

Thanks again!

**Comment by aliannejadi** [comment]
My pleasure.

**Comment by ShiyuNee** [comment]
> My pleasure.

Hope your research will get better and better.

**Comment by ShiyuNee** [comment]
I found that there are 41 topics that have only one facet_id and the number is larger than 39.

Is it because that other topics can also have onle one facet?

**Comment by aliannejadi** [comment]
I'd have to check to be able to answer this question, but it might have happened because we removed the facets for which there were no relevant documents in the qrels.

**Comment by ShiyuNee** [comment]
> I'd have to check to be able to answer this question, but it might have happened because we removed the facets for which there were no relevant documents in the qrels.

I think the ids of the two additional topics may be 6 and 19(not single topics).

**Comment by ShiyuNee** [comment]
> 

Because 6 and 19 are also topic_ids in Qulac(1 to 200 without 95 and 100), if topic_ids for qulac are the same as that in ClariQ.

**Comment by aliannejadi** [comment]
Yes, that's right. The ID's are the same and these were already part of qulac.

**Comment by ShiyuNee** [comment]
> 

I get it, thanks!
