### ISSUE TITLE
Consistency of Document IDs in test.qrel, train.qrel, and dev.qrel with top10k

### ISSUE THREAD

**Issue by samanehrad** [aliannejadi/ClariQ#8]
Hi,
I want to express my appreciation for the excellent instruction you’ve provided. However, I am encountering some difficulties with certain aspects and would be grateful for your assistance in clarifying the following point:
I have compared the document IDs present in the files test.qrel, train.qrel, and dev.qrel with those in the top10k file. I expected that most of the relevant document IDs from the test.qrel, train.qrel, and dev.qrel files would be included in the top10k file, as it is supposed to contain the top 10,000 documents for each topic. For example, if the train.qrel file lists a document with a label of 4 for a particular facet of a topic, I anticipated that this document would be among the top 10,000 documents for that topic in the top10k file. Could you please clarify whether my understanding is correct or if there might be an issue with this expectation?
Thank you very much for your time and assistance. I look forward to your response.

Best regards,
Samaneh

**Comment by aliannejadi** [comment]
Thanks for your interest. 
There is no guarantee that the documents in the qrel files appear in the top10k ranking. The top10k file is generated by simply ranking the documents using BM25, which means that it can contain some of the relevant documents but there is no guarantee.
